blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail, name='post_detail'),
    path('post/<int:post_id>/share/', views.post_share, name='post_share'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().\
            filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(unique_for_date='publish')
    author = models.ForeignKey(User, related_name='posts',
                               on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments',
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

from .models import Comment


class PostShareForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail

from .models import Post
from .forms import CommentForm, PostShareForm


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'posts': posts})


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, status='published',
                             slug=slug,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    form = CommentForm()
    new_comment = None
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()

    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'form': form,
                                                     'new_comment': new_comment,
                                                     'comments': comments})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = PostShareForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} recommends you to read "{post.title}"'
            message = f'Read "{post.title}" at {post_url}\n\n'\
                f'{cd["name"]}\'s comments: {cd["comment"]}'
            send_mail(subject, message, cd['email'], [cd['to']])
            sent = True
    else:
        form = PostShareForm()
    return render(request, 'blog/post/share.html',
                  {'post': post, 'form': form, 'sent': sent})

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}{% endblock title %}</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
    </head>

    <body>
        <div id="main-container">
            <div class="header">
                    <img src="{% static 'images/blogLogo.jpg' %}" class="blog-logo" / >
                    <div class="navbar_links">
                        <a href="#">Home</a>
                        <a href="#">Menu</a>
                        <a href="#">About</a>
                        <a href="#">Contact Us</a>
                    </div>
            </div>

            <div class="section">
                <div class="content">
                    {% block content%}
                    {% endblock content%}
                </div>

                <div class="side">
                    <div class="left-open-btn">
                        <i class="fa fa-arrow-left"></i>
                    </div>

                    <div class="list-box">
                        <h3>
                            Most popular posts
                        </h3>
                        <div>
                            <a href="#"><span>1</span>List Item One</a>
                            <a href="#"><span>2</span>List Item Two</a>
                            <a href="#"><span>3</span>List Item Three</a>
                            <a href="#"><span>4</span>List Item Four</a>
                            <a href="#"><span>5</span>List Item Five</a>
                            <a href="#"><span>6</span>List Item Six</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer pt-3">
            <div class="d-flex justify-content-around">
                <span class="logo"> MyBlog </span>
                <div class="footer_links">
                    <a href="#">Home</a>
                    <a href="#">Menu</a>
                    <a href="#">About</a>
                    <a href="#">Contact Us</a>
                </div>
            </div>
            <br />
            <hr id="footer_hr" />
            <div id="footer_icons">
                <a href="#"><i class="fa fa-youtube fa-2x"></i></a>
                <a href="#"><i class="fa fa-facebook fa-2x"></i></a>
                <a href="#"><i class="fa fa-instagram fa-2x"></i></a>
                <a href="#"><i class="fa fa-telegram fa-2x"></i></a>
            </div>
        </div>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"
        ></script>

        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

                <!-- <form class="search-form d-flex">
                    <input
                        class="form-control me-2"
                        type="search"
                        placeholder="Search"
                        aria-label="Search"
                    />
                    <button
                        class="btn btn-outline-success"
                        type="submit"
                    >
                        Search
                    </button>
                </form> -->

blog/templates/blog/pagination.html
<div id="pagination">
    <span>
        {% if page.has_previous %}
        <a href="/?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span>Page {{ page.number }} of {{ page.paginator.num_pages }}</span>

        {% if page.has_next %}
        <a href="/?page={{ page.next_page_number }}">Next</a>
        {% endif %}

    </span>
</div>

blog/templates/blog/post/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<h2>{{ post.title }}</h2>
<p>
    {{ post.body|linebreaks }}
</p>
<h5>Post published at {{ post.publish }}</h5>
<p><a href="{% url 'blog:post_share' post.id %}">Share this post</a></p>

{% if new_comment %}
<p>Your comment added.</p>
{% else %}
<h3>Leave a comment</h3>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Leave comment"></p>
</form>
{% endif %}

{% for comment in comments %}
<div>
    <p>
        Comment {{ forloop.counter }} by {{ comment.name }}.
        <span>{{ comment.created }}</span>
    </p>
    <div>
        {{ comment.body|linebreaks }}
    </div>
</div>
{% empty %}
<p>No comments yet</p>
{% endfor %}


{% endblock content %}

blog/templates/blog/post/list.html
{% extends 'base.html' %} {% block title %} All posts {% endblock title %}
{% block content %} {% for post in posts %}
<div class="post">
    <h3 class="title">
        <a href="{{ post.get_absolute_url}}"> {{ post.title }} </a>
    </h3>

    <p>{{ post.body|truncatewords:50|linebreaks }}</p>
    <a href="{{ post.get_absolute_url }}" class="btn-read"><span>Read more</span></a>
    <h6 class="pub-date">{{ post.publish }}</h6>
</div>
{% empty %} No posts yet. {% endfor %} {% include 'blog/pagination.html' with page=posts %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'base.html' %}

{% block title %}
Share post
{% endblock title %}

{% block content %}
{% if sent %}
<h2>Message sent to {{ form.cleaned_data.to }} successfully</h2>
{% else %}
<h1>Use the following form to share the post</h1>
<form action="{% url 'blog:post_share' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Share post"></p>
</form>
{% endif %}
{% endblock content %}